#!/usr/bin/env bash

trapped() {
  echo -e "\nTrapped--quitting\n"
  exit 200
}

trap "trapped" 1 2 3 4 5 6 7 8 11 15

sesh=${1:-""}
paramfile=${2:-"${sesh}.prm"}
np=${3:-8}

seshplate=${sesh}.template

[[ -z $sesh ]] && {
  echo "No session passed, quitting."
  exit 50
} || :

! [[ -f $seshplate ]] && {
  echo "Template file ${sesh}.template not present, quitting."    
  exit 51
} || :

! [[ -f $paramfile ]] && {
  echo "Parameter file $paramfile not present, quitting."    
  exit 52
} || :

savdir=sav
vtkdir=vtk

! [[ -d $savdir ]] && mkdir -p $savdir || :
! [[ -d $vtkdir ]] && mkdir -p $vtkdir || :

run() {
  mpirun -n $np dns_mp ${sesh}
}

vtk() {
  vtk_rect_rec="${1}"
  vtk_cyln_rec="${2}"
  sem2vtk -m ${sesh}.msh -o "${vtk_rect_rec}.vtk" ${sesh}.fld
  sem2vtk -c -m ${sesh}.msh -o "${vtk_cyln_rec}.vtk" ${sesh}.fld
  rm tmp.*
}

rst() {
  cp ${sesh}.fld ${sesh}.rst
}

sav() {
  job_id="${1}"
  cp ${sesh}.fld ${savdir}/${sesh}.${job_id}.fld
  cp ${sesh}.mdl ${savdir}/${sesh}.${job_id}.mdl
  cp ${sesh}.his ${savdir}/${sesh}.${job_id}.his
}

mod_session() {
  re="${1}"
  dt="${2}"
  ns="${3}"
  sed -e "s/{{reynolds}}/${re}/g; 
          s/{{timestep}}/${dt}/g;  
          s/{{iterations}}/${ns}/g" ${seshplate} > ${sesh} || {
    echo "Template file error, quitting." 
    exit 70
  }
  echo "Running for Re = $re, dt = $dt, number of iterations = $ns"
}

combine_mdl() {
  file="${1}"
  fid=$(basename ${file#*.} .mdl)
  re=$(awk 'NR=='$n'+1 {print $1}' ${seshplate})
  python << __EOF
from numpy import *
re    = float($re) if $re > 0 else 1.
mode0 = loadtxt('$file').T[2,::8] 
avg   = average(mode0[-100:])/(re**2.)
print( '{:5.5g} {:5.5g}'.format($re,avg) )
__EOF
}

export -f combine_mdl

mapfile -t res < <(awk '{print $1}' $paramfile)
mapfile -t dts < <(awk '{print $2}' $paramfile)
mapfile -t nss < <(awk '{print $3}' $paramfile)

[[ -f ${sesh}.rst ]] && rm ${sesh}.rst || :

mod_session "${res[0]}" "${dts[0]}" "${nss[0]}"
meshpr    ${sesh} > ${sesh}.msh
enumerate ${sesh} > ${sesh}.num

for k in ${!nss[@]}; do
  mod_session "${res[$k]}" "${dts[$k]}" "${nss[$k]}"
  run
  rst
  sav "${k}"
  vtk "${vtkdir}/r.${k}" "${vtkdir}/c.${k}"
done

tmp_combine=/tmp/combine.mdl
: > $tmp_combine
popts='--will-cite --gnu'

parallel $popts combine_mdl ::: ${savdif}/*.mdl >> $tmp_combine
sort -g $tmp_combine > ${sesh}.master.mdl
rm $tmp_combine
