#!/usr/bin/env bash

sesh=${1:-""}
paramfile=${2:-"${sesh}.prm"}
np=${3:-8}

[[ -z $sesh ]] && {
  echo "No session passed, quitting."
  exit 50
} || :

! [[ -f $sesh ]] && {
  echo "Session file $sesh not present, quitting."    
  exit 51
} || :

! [[ -f $paramfile ]] && {
  echo "Parameter file $paramfile not present, quitting."    
  exit 52
} || :

savdir=sav
vtkdir=vtk

! [[ -d $savdir ]] && mkdir -p $savdir || :
! [[ -d $vtkdir ]] && mkdir -p $vtkdir || :

run() {
  mpirun -n $np dns_mp ${sesh}
}

vtk() {
  vtk_rect_rec="${1}"
  vtk_cyln_rec="${2}"
  sem2vtk -m ${sesh}.msh -o "${vtk_rect_rec}.vtk" ${sesh}.fld
  sem2vtk -c -m ${sesh}.msh -o "${vtk_cyln_rec}.vtk" ${sesh}.fld
  rm tmp.*
}

rst() {
  cp ${sesh}.fld ${sesh}.rst
}

sav() {
  job_id="${1}"
  cp ${sesh}.fld ${savdir}/${sesh}.${job_id}.fld
  cp ${sesh}.mdl ${savdir}/${sesh}.${job_id}.mdl
  cp ${sesh}.his ${savdir}/${sesh}.${job_id}.his
}


mod_session() {
  re="${1}"
  dt="${2}"
  ns="${3}"
  sed                                   \
    -e 's/{{reynolds}}/'"${re}"'/'      \
    -e 's/{{timestep}}/'"${dt}"'/'      \
    -e 's/{{iterations}}/'"${ns}"'/'    \
    ${sesh}.template > ${sesh} || {
    echo "Template file error, quitting." 
    exit 70
  }
}

mapfile res < <(awk '{print $1}' $paramfile)
mapfile dts < <(awk '{print $2}' $paramfile)
mapfile nss < <(awk '{print $3}' $paramfile)

[[ -f ${sesh}.rst ]] && rm ${sesh}.rst || :

meshpr    ${sesh} > ${sesh}.msh
enumerate ${sesh} > ${sesh}.num

for k in ${!nss[@]}; do
  mod_session "${res[$k]}" "${dts[$k]}" "${nss[$k]}"
  run
  rst
  sav "${k}"
  vtk "${vtkdir}/r.${k}" "${vtkdir}/c.${k}"
done
